# Generated by Django 5.1.15 on 2026-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refnum", models.CharField(db_index=True, max_length=60, unique=True)),
                ("nom_client", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["nom_client"],
            },
        ),
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("id_fid", models.CharField(blank=True, max_length=20)),
                ("date_reception", models.CharField(blank=True, max_length=20)),
                ("site", models.CharField(blank=True, max_length=120)),
                ("agent_fidelisation", models.CharField(blank=True, max_length=120)),
                ("refnum", models.CharField(blank=True, db_index=True, max_length=60)),
                ("nom_client", models.CharField(blank=True, max_length=200)),
                ("technologie", models.CharField(blank=True, max_length=80)),
                ("ref_produit", models.CharField(blank=True, max_length=80)),
                ("ancien_produit", models.CharField(blank=True, max_length=160)),
                ("ancien_mensualite_ttc", models.FloatField(default=0)),
                ("date_contrat", models.CharField(blank=True, max_length=20)),
                ("requete_client", models.CharField(blank=True, max_length=80)),
                ("motif", models.CharField(blank=True, max_length=160)),
                ("information_libre", models.TextField(blank=True)),
                ("action", models.CharField(blank=True, max_length=80)),
                (
                    "niveau_decision",
                    models.CharField(blank=True, default="En Attente", max_length=40),
                ),
                ("date_cloture", models.CharField(blank=True, max_length=20)),
                ("agent_confirmation", models.CharField(blank=True, max_length=120)),
                ("date_prevue_execution", models.CharField(blank=True, max_length=20)),
                ("priorite", models.CharField(blank=True, max_length=40)),
                ("ref_nouv_produit", models.CharField(blank=True, max_length=80)),
                ("nouveau_produit", models.CharField(blank=True, max_length=160)),
                ("nouveau_mensualite_ttc", models.FloatField(default=0)),
                ("nouveau_nom", models.CharField(blank=True, max_length=200)),
                ("date_nv_contrat", models.CharField(blank=True, max_length=20)),
                ("audit", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_reception", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RefItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=40)),
                ("value", models.CharField(max_length=160)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "value"],
                "unique_together": {("category", "value")},
            },
        ),
    ]
